### PR TITLE
Remove disco dependency for testing. Fix db launching. Add sklearn dependency.

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by acrellin** [comment]
The tests won't pass without Disco - why remove the dependency?

**Comment by stefanv** [comment]
Disco is only needed on the worker nodes, not so?

**Comment by stefanv** [comment]
Also, there seems to be implicit logic in the code for dealing with the case when Disco is missing.

**Comment by acrellin** [comment]
Disco is needed on the master, which then spawns off portions of a job to
the various workers.

**Comment by acrellin** [comment]
The master and all of the nodes need to have Disco installed.

**Comment by acrellin** [comment]
Thanks for the reminder - I changed some of the checks to see if Disco is
installed for testing purposes and need to address them.

**Comment by stefanv** [comment]
Thanks--requiring Disco on the main server makes sense i.t.o. the discussion we had on the whiteboard the other day.   I'll put the check back in as soon as I get the tests running.

**Comment by stefanv** [comment]
Thinking about it, I'm not sure why disco is utilized this way.  Let's check in about this on Monday.

**Pull request merged**
