### PR TITLE
Fix broken pipe error in frontend tests (fixes #76)

### LINKED ISSUE #76: Fix exceptions raised during Casper tests
Of the form:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51132)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

See also: http://stackoverflow.com/a/22560461/214686

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by stefanv** [comment]
Fantastic, thanks Ari! Can you explain what was wrong?

**Comment by acrellin** [comment]
Well, I've fixed most of them - waiting on the latest build to see about the last remaining error. In one or two places I had missed a double submit! The last error is a bit more mysterious...

**Comment by acrellin** [comment]
I have no broken pipe errors on my machine, but I saw there was one remaining during the Drone build

**Comment by acrellin** [comment]
Thus the premature PR

**Comment by acrellin** [comment]
Success!

**Comment by acrellin** [comment]
Alright folks, the error is gone - please review when you have a chance.

**Comment by bnaul** [comment]
Looks reasonable to me but the frontend tests have never worked on OS X (and still do not) so I can't really verify anything...

**Pull request merged**
