### PR TITLE
Python3 fixes: str encodings, iterator usage

### LINKED ISSUE #75: Python3 Compatibility
Seems like we're pretty close at this point, should we go ahead and try to fix the remaining few problems? @stefanv, did you want to take care of this or should @acrellin or I?

### PR DESCRIPTION
**Pull request by bnaul**
This should fix all the remaining Python3 incompatibilities (which were almost all problems with the test code and how data read from files/web requests were being compared to known string values).

Fixes #75.

### CODE REVIEW

**Comment by bnaul** [comment]
1. Can someone run the frontend tests on Python3 for me?
2. Is it possible to have Drone test on both Python2 and Python3? I know this is straightforward with Travis but I'm not sure how to do it with Drone.

**Comment by acrellin** [comment]
@bnaul, running the frontend tests under Python 3 yields the attached output.

[test_frontend_output.txt](https://github.com/mltsp/mltsp/files/50200/test_frontend_output.txt)
[celery.log.txt](https://github.com/mltsp/mltsp/files/50206/celery.log.txt)

**Comment by bnaul** [comment]
Is your Celery process using Python3 as well? Could it be leftover in the background from a Python2 virtualenv? If you can run the backend tests but not the frontend then I'm concerned, but if you can't run either then it's probably a configuration issue.

**Comment by acrellin** [comment]
I started Celery from the Python 3 env. Here's some output from the backend tests:
```
Traceback (most recent call last):
  File "/tmp/mltsp/mltsp/tests/test_flask_app.py", line 1491, in test_prediction_proc
    "TESTRUN_215153_metadata.dat"))
  File "/tmp/mltsp/mltsp/Flask/flask_app.py", line 2149, in prediction_proc
    pred_results_dict=pred_results_dict)
  File "/tmp/mltsp/mltsp/Flask/flask_app.py", line 456, in update_prediction_entry_with_results
    .update(info_dict).run(g.rdb_conn)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/site-packages/rethinkdb/ast.py", line 95, in run
    return c._start(self, **global_optargs)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/site-packages/rethinkdb/net.py", line 238, in _start
    return self._send_query(query, global_optargs)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/site-packages/rethinkdb/net.py", line 330, in _send_query
    query_str = query.serialize().encode('utf-8')
  File "/home/arien/anaconda/envs/py3/lib/python3.3/site-packages/rethinkdb/net.py", line 52, in serialize
    return json.dumps(res, ensure_ascii=False, allow_nan=False)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/json/__init__.py", line 240, in dumps
    **kw).encode(obj)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/json/encoder.py", line 191, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/json/encoder.py", line 249, in iterencode
    return _iterencode(o, 0)
  File "/home/arien/anaconda/envs/py3/lib/python3.3/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
nose.proxy.TypeError: array([[  2.62952836e+03,   2.80593132e+03,   2.81490280e+03,
          2.84087507e+03,   2.84385544e+03,   2.85190360e+03,
          2.85878590e+03,   2.87580358e+03,   2.87776851e+03,
          2.88074438e+03,   2.88376435e+03,   2.88572244e+03,
          2.89573375e+03,   2.89773746e+03,   2.90269841e+03,
          2.90567732e+03,   2.90868856e+03,   2.91072017e+03,
          2.91267879e+03,   2.91566041e+03,   2.91763089e+03,
          2.92365656e+03,   2.92665262e+03,   2.92865138e+03,
          2.93064852e+03,   2.93463533e+03,   2.93663595e+03,
          2.93964986e+03,   2.94358775e+03,   2.94558683e+03,
          2.95058475e+03,   2.95259876e+03,   2.95460462e+03,
          2.95660356e+03,   2.95860234e+03,   2.96553482e+03,
          2.96955975e+03,   3.17993673e+03,   3.18692905e+03,
          3.19089194e+03,   3.27960736e+03,   3.29956018e+03,
          3.34861344e+03,   3.34861897e+03,   3.54388159e+03,
          3.54787057e+03,   3.55285137e+03,   3.56283404e+03,
          3.56981581e+03,   3.57181193e+03,   3.58377362e+03,
          3.59274773e+03,   3.59673552e+03,   3.60269825e+03,
          3.60272875e+03,   3.60273115e+03,   3.60276166e+03,
          3.61768923e+03,   3.62067678e+03,   3.62466643e+03,
          3.62865738e+03,   3.63463799e+03,   3.63962616e+03,
          3.64261849e+03,   3.64660860e+03,   3.65258716e+03,
          3.65458752e+03,   3.65757887e+03,   3.66255624e+03,
          3.66555676e+03,   3.67053595e+03,   3.67452903e+03,
          3.67751570e+03,   3.89292012e+03,   3.89790905e+03,
          3.90090089e+03,   3.90389143e+03,   3.90788202e+03,
          3.91287059e+03,   3.98168065e+03,   4.25393171e+03,
          4.25892019e+03,   4.27388102e+03,   4.28385713e+03,
          4.28585247e+03,   4.29083492e+03,   4.29383233e+03,
          4.29682270e+03,   4.30180401e+03,   4.30380372e+03,
          4.30579442e+03,   4.30779360e+03,   4.30978321e+03,
          4.31178690e+03,   4.31975605e+03,   4.33071942e+03,
          4.33272594e+03,   4.33471692e+03,   4.34768766e+03,
          4.35067822e+03,   4.35366616e+03,   4.35665611e+03,
          4.35964771e+03,   4.36264625e+03,   4.36464093e+03,
          4.37261611e+03,   4.37660823e+03,   4.37959932e+03,
          4.38258816e+03,   4.38557692e+03,   4.38758184e+03,
          4.38956873e+03,   4.40352749e+03,   4.40951910e+03,
          4.63192369e+03,   4.64092177e+03,   4.64593574e+03,
          4.64891382e+03,   4.66187572e+03,   4.66484448e+03,
          4.66684960e+03,   4.67286644e+03,   4.67585983e+03,
          4.67980544e+03,   4.68280765e+03,   4.68480805e+03,
          4.68680145e+03,   4.69078818e+03,   4.69378595e+03,
          4.70179238e+03,   4.70474575e+03,   4.70773783e+03,
          4.71672629e+03,   4.72071771e+03,   4.72272674e+03,
          4.72867680e+03,   4.73072439e+03,   4.73376544e+03,
          4.73964942e+03,   4.74470318e+03,   4.74670666e+03,
          4.74871770e+03,   4.75464412e+03,   4.75666845e+03,
          4.75962208e+03,   4.76260727e+03,   4.76759675e+03,
          4.77461890e+03,   4.77662458e+03,   4.78257845e+03,
          4.78462777e+03,   4.79754233e+03,   4.80354779e+03,
          4.81654062e+03,   4.99293716e+03,   5.01486617e+03,
          5.01790202e+03,   5.02387545e+03,   5.04877738e+03,
          5.06377957e+03,   5.07276379e+03,   5.07573142e+03,
          5.08276421e+03,   5.08475892e+03,   5.08974278e+03,
          5.09268685e+03,   5.10565881e+03,   5.12266529e+03,
          5.13157904e+03,   5.14557672e+03],
       [  9.51100000e+00,   1.27190000e+01,   1.26950000e+01,
          1.24830000e+01,   1.27970000e+01,   1.22600000e+01,
          1.20170000e+01,   1.12800000e+01,   1.11340000e+01,
          1.10120000e+01,   1.08100000e+01,   1.07370000e+01,
          1.03140000e+01,   9.96800000e+00,   1.01180000e+01,
          1.00450000e+01,   1.00080000e+01,   9.95200000e+00,
          9.94800000e+00,   9.90800000e+00,   9.90900000e+00,
          9.83100000e+00,   9.78200000e+00,   9.79000000e+00,
          9.77900000e+00,   9.71800000e+00,   9.65600000e+00,
          9.62700000e+00,   9.56700000e+00,   9.49300000e+00,
          9.28600000e+00,   9.23300000e+00,   9.12600000e+00,
          9.04600000e+00,   8.94700000e+00,   8.72400000e+00,
          8.53800000e+00,   1.20490000e+01,   1.19270000e+01,
          1.18020000e+01,   8.65300000e+00,   8.09300000e+00,
          9.58300000e+00,   9.60900000e+00,   9.67800000e+00,
          9.57800000e+00,   9.41200000e+00,   9.19200000e+00,
          9.08700000e+00,   9.05700000e+00,   8.81400000e+00,
          8.55100000e+00,   8.42000000e+00,   8.20200000e+00,
          8.21300000e+00,   8.21500000e+00,   8.19900000e+00,
          7.82200000e+00,   7.82100000e+00,   7.91600000e+00,
          7.98400000e+00,   8.09600000e+00,   8.21900000e+00,
          8.27700000e+00,   8.37600000e+00,   8.55300000e+00,
          8.60800000e+00,   8.74300000e+00,   8.92900000e+00,
          9.03500000e+00,   9.23500000e+00,   9.41400000e+00,
          9.53100000e+00,   9.73500000e+00,   9.68300000e+00,
          9.60500000e+00,   9.53800000e+00,   9.42200000e+00,
          9.29400000e+00,   9.00800000e+00,   8.52100000e+00,
          8.48700000e+00,   8.32900000e+00,   8.40700000e+00,
          8.42700000e+00,   8.50400000e+00,   8.52300000e+00,
          8.62400000e+00,   8.87300000e+00,   8.87000000e+00,
          8.89300000e+00,   9.02500000e+00,   9.11200000e+00,
          9.17400000e+00,   9.46200000e+00,   9.86600000e+00,
          9.97500000e+00,   1.00400000e+01,   1.04760000e+01,
          1.05800000e+01,   1.06560000e+01,   1.08000000e+01,
          1.08460000e+01,   1.09820000e+01,   1.10620000e+01,
          1.12820000e+01,   1.14710000e+01,   1.16630000e+01,
          1.16540000e+01,   1.18570000e+01,   1.19250000e+01,
          1.19390000e+01,   1.22510000e+01,   1.25400000e+01,
          9.77700000e+00,   9.96800000e+00,   1.00810000e+01,
          1.01030000e+01,   1.04580000e+01,   1.05480000e+01,
          1.06500000e+01,   1.08060000e+01,   1.09290000e+01,
          1.10500000e+01,   1.11710000e+01,   1.12460000e+01,
          1.12980000e+01,   1.13780000e+01,   1.14990000e+01,
          1.16580000e+01,   1.17710000e+01,   1.17550000e+01,
          1.19930000e+01,   1.20030000e+01,   1.24260000e+01,
          1.22390000e+01,   1.22160000e+01,   1.23070000e+01,
          1.23580000e+01,   1.23250000e+01,   1.25120000e+01,
          1.25130000e+01,   1.22630000e+01,   1.25920000e+01,
          1.24510000e+01,   1.24480000e+01,   1.21770000e+01,
          1.23520000e+01,   1.22940000e+01,   1.24170000e+01,
          1.22080000e+01,   1.17960000e+01,   1.15680000e+01,
          1.09330000e+01,   1.04430000e+01,   1.12450000e+01,
          1.13320000e+01,   1.14020000e+01,   1.19920000e+01,
          1.20870000e+01,   1.19680000e+01,   1.19940000e+01,
          1.20560000e+01,   1.19780000e+01,   1.18470000e+01,
          1.19460000e+01,   1.14140000e+01,   1.06790000e+01,
          1.03440000e+01,   9.75500000e+00],
       [  4.20000000e-02,   3.80000000e-02,   3.80000000e-02,
          3.60000000e-02,   3.90000000e-02,   3.70000000e-02,
          3.20000000e-02,   3.40000000e-02,   3.40000000e-02,
          4.70000000e-02,   3.30000000e-02,   3.80000000e-02,
          4.00000000e-02,   3.80000000e-02,   3.80000000e-02,
          3.30000000e-02,   3.50000000e-02,   3.30000000e-02,
          3.50000000e-02,   3.40000000e-02,   3.70000000e-02,
          4.10000000e-02,   3.50000000e-02,   3.70000000e-02,
          3.50000000e-02,   3.50000000e-02,   5.60000000e-02,
          3.60000000e-02,   3.80000000e-02,   3.90000000e-02,
          4.00000000e-02,   3.80000000e-02,   3.80000000e-02,
          3.80000000e-02,   5.10000000e-02,   3.70000000e-02,
          3.40000000e-02,   3.90000000e-02,   4.30000000e-02,
          4.30000000e-02,   4.30000000e-02,   4.20000000e-02,
          5.40000000e-02,   4.70000000e-02,   4.40000000e-02,
          5.10000000e-02,   4.40000000e-02,   3.70000000e-02,
          3.80000000e-02,   4.10000000e-02,   4.30000000e-02,
          4.20000000e-02,   3.70000000e-02,   5.30000000e-02,
          4.70000000e-02,   4.70000000e-02,   4.80000000e-02,
          4.50000000e-02,   5.00000000e-02,   3.70000000e-02,
          4.00000000e-02,   4.90000000e-02,   3.90000000e-02,
          4.10000000e-02,   4.10000000e-02,   4.60000000e-02,
          4.60000000e-02,   4.60000000e-02,   5.60000000e-02,
          5.00000000e-02,   3.70000000e-02,   4.00000000e-02,
          4.00000000e-02,   3.70000000e-02,   5.40000000e-02,
          4.70000000e-02,   3.90000000e-02,   4.00000000e-02,
          3.90000000e-02,   4.60000000e-02,   4.40000000e-02,
          3.70000000e-02,   4.50000000e-02,   4.20000000e-02,
          4.20000000e-02,   4.90000000e-02,   4.20000000e-02,
          4.20000000e-02,   5.40000000e-02,   4.50000000e-02,
          3.80000000e-02,   5.40000000e-02,   5.90000000e-02,
          4.00000000e-02,   3.50000000e-02,   3.80000000e-02,
          3.70000000e-02,   3.50000000e-02,   4.50000000e-02,
          3.80000000e-02,   3.70000000e-02,   3.80000000e-02,
          3.70000000e-02,   3.40000000e-02,   3.50000000e-02,
          4.50000000e-02,   3.70000000e-02,   5.70000000e-02,
          5.10000000e-02,   3.50000000e-02,   3.50000000e-02,
          4.40000000e-02,   3.70000000e-02,   4.00000000e-02,
          3.90000000e-02,   5.00000000e-02,   4.10000000e-02,
          3.70000000e-02,   4.00000000e-02,   3.90000000e-02,
          3.80000000e-02,   3.60000000e-02,   3.60000000e-02,
          3.60000000e-02,   3.70000000e-02,   4.00000000e-02,
          3.90000000e-02,   3.50000000e-02,   5.10000000e-02,
          3.50000000e-02,   3.90000000e-02,   4.60000000e-02,
          4.00000000e-02,   4.20000000e-02,   4.40000000e-02,
          4.30000000e-02,   3.90000000e-02,   5.60000000e-02,
          3.60000000e-02,   3.70000000e-02,   4.00000000e-02,
          3.80000000e-02,   5.60000000e-02,   4.80000000e-02,
          4.00000000e-02,   4.10000000e-02,   4.10000000e-02,
          4.30000000e-02,   4.60000000e-02,   4.70000000e-02,
          4.90000000e-02,   5.10000000e-02,   4.20000000e-02,
          5.20000000e-02,   5.60000000e-02,   5.60000000e-02,
          6.10000000e-02,   5.50000000e-02,   5.40000000e-02,
          5.70000000e-02,   5.60000000e-02,   5.90000000e-02,
          5.70000000e-02,   4.90000000e-02,   5.10000000e-02,
          4.70000000e-02,   6.00000000e-02,   6.20000000e-02,
          5.80000000e-02,   6.00000000e-02]]) is not JSON serializable
```

**Comment by acrellin** [comment]
I get that same error several times during the backend tests

**Comment by bnaul** [comment]
Do the backend tests run for you under Python2? That doesn't seem like a 2 vs. 3 error but Drone is happy.

**Comment by acrellin** [comment]
Shoot, my Python installation has some issues... Drone does the frontend tests, too, though - they just never ran because of a PhantomJS version issue. I'm surprised it came back green... The same thing came up on my machine and I fixed it with the steps outlined here: https://gist.github.com/dominicsayers/5736130

**Comment by acrellin** [comment]
If you click the green checkmark (http://nipy.bic.berkeley.edu:8080/github.com/mltsp/mltsp/bnaul-eeg_example/88cef1e818ab968263229c6c664c82db7f16365e) you can see that the build never actually completed the frontend tests because of the PhantomJS version error, yet still came back green. So that needs to be fixed in the Drone `build.sh` script.

**Comment by bnaul** [comment]
Yeah, I see...sort of hard for me to test on OS X, can you take a shot at adding those lines to the script and seeing if that fixes it? It seems separate from this PR since there's no way any of this broke the frontend tests, I was just wondering if there were any more Python3 issues hiding out there.

**Comment by bnaul** [comment]
Should we go ahead and merge this? It should be unrelated to the Drone issues; if that's not going to be straightforward to resolve we could open a separate issue for it.

**Comment by acrellin** [comment]
:+1: from me

**Pull request merged**
