### PR TITLE
Change inline functions to static

### PR DESCRIPTION
**Pull request by stefanv**
@bnaul Can you please check whether this fixes your problem?

### CODE REVIEW

**Comment by bnaul** [comment]
Hi Stefan,

Looks like this helped but now the error is:

#########      Error:    flask_app.featurize_proc:
dlopen(/Users/brettnaul/Dropbox/Documents/mltsp/mltsp/TCP/Software/feature_extract/Code/extractors/common_functions/_lomb_scargle.so,
2): Symbol not found: _get_eigs

The command we were trying was "from
mltsp.TCP.Software.feature_extract.Code.extractors.common_functions import
_lomb_scargle".

Brett

**Comment by stefanv** [comment]
Excellent, then that strategy works. I'll fix the other one too.

**Comment by stefanv** [comment]
@bnaul Please try again!

**Comment by bnaul** [comment]
_tred2 in _eigs.h is the last culprit; I tried changing it to static inline
void and that seems to be the last remaining issue (i.e. import
_lomb_scorgle works for me with that change).

**Comment by stefanv** [comment]
Excellent, thanks for the feedback.  Please test this version and 
merge the PR at your convenience, if you're satisfied.

**Pull request merged**
