### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by stefanv**
@bnaul Please do a quick check for me before I tag 0.3.

### CODE REVIEW

**Comment by bnaul** [comment]
Can't test anything from my phone but looks good enough to me.

**Comment by acrellin** [comment]
Why are the tests failing?

**Comment by stefanv** [comment]
@acrellin Because I am now using pip to install dependencies, and some installs are failing.  Working on fixing that now.

**Comment by stefanv** [comment]
Mergin this so that I can tag the release.

**Pull request merged**
