### PR TITLE
Add frontend test support

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by stefanv** [comment]
@acrellin I was hoping you could check this PR to see which tests are broken on your system still so I could fix them.  But now I'm sure that will become evident pretty quickly :)

**Comment by stefanv** [comment]
And once I have Drone working, this kind of checking will be done by "the machine".

**Comment by acrellin** [comment]
Thanks Stefan - I've added test output to the shared DB folder.

**Comment by stefanv** [comment]
Hey, Ari

On 2015-04-22 17:35:02, acrellin <notifications@github.com> wrote:
> Thanks Stefan - I've added test output to the shared DB folder.

Dropbox says it is up to date, but I don't see it--where should I 
look?

Also, if you can fix the easy looking ones on your machine, that 
would be helpful since it's very hard for me to debug on my end.

Stéfan

**Comment by acrellin** [comment]
It's in the shared folder mltp - two files starting with
"casperjs_rebase..."
I'll fix the easy ones on my machine!

**Comment by stefanv** [comment]
Found them, thanks!  Looks like I should be able to fix those fairly easily.

**Pull request merged**
