### PR TITLE
Add `period_fast` feature based on gatspy LombScargleFast (fixes #111)

### LINKED ISSUE #111: Use LombScargleFast from gatspy?
I did a quick benchmark of our Lomb-Scargle implementation versus the ones in `gatspy`.
## Benchmark
```python
N = 2001
times = np.sort(np.random.random(size=N))
values = 8 * np.sin(2*np.pi*times*5.3 + 0.1) + np.random.normal(scale=0.1, size=N)  # sinusoidal-ish
errors = np.random.exponential(scale=0.1, size=N)

# Use parameters comparable to our LS implementation
opt_args = {'period_range': (1./33., times.max()), 'quiet': True}
# 8-harmonic model with regularization (our default)
%timeit gatspy.periodic.LombScargle(Nterms=8, regularization=1., regularize_by_trace=False, fit_period=True, optimizer_kwds=opt_args).fit(times, values, errors)
# 1-harmonic model without regularization (Fast version)
%timeit gatspy.periodic.LombScargleFast(fit_period=True, optimizer_kwds=opt_args).fit(times, values, errors)

# Use roughly the same number of grid points as gatspy chooses
numf = 1500
df = (33 - 1./times.max()) / numf
# 8-harmonic model with regularization (our default)
%timeit fit_lomb_scargle(times, values, errors, 1/times.max(), df, numf)
# 1-harmonic model without regularization (Fast version)
%timeit fit_lomb_scargle(times, values, errors, 1/times.max(), df, numf, lambda0=0., nharm=1)
```

## Output
```
1 loops, best of 3:     962 ms per loop        # gatspy, full model
100 loops, best of 3:    22 ms per loop        # gatspy, simple model
1 loops, best of 3:     888 ms per loop        # ours, full model
1 loops, best of 3:     239 ms per loop        # ours, simple model
```

## Conclusion
The `LombScargleFast` function from `gatspy`, which fits a much simpler model to the data, is much faster than our C implementation. I think it would be good to add some features based on `LombScargleFast`, since they would be faster and easier to understand for non-expert users. We could leave in the existing implementation as it computes some additional statistical quantities which the `gatspy` functions do not, but these seem like features that only really expert users would be interested in.

Thoughts?

### PR DESCRIPTION
**Pull request by bnaul**
Fits a simple sinuosidal model

    y(t) = A sin(2*pi*w*t) + B cos(2*pi*w*t) + c

and returns the estimated period `1/w`. This is not a replacement for our Lomb-Scargle implementation, which we decided to keep as-is for now. It just adds an alternative that is simpler but much faster; for example, estimating periods for the `datasets.andrzejak` EEG data takes 18.3s with this method vs. 15m12s with our existing Lomb-Scargle.

### CODE REVIEW

**Comment by acrellin** [comment]
:+1: 
Looks good

**Comment by bnaul** [comment]
Fixed the test errors, should be ready to go now :rocket:

**Comment by stefanv** [comment]
@bnaul Did we merge a broken PR here?!

**Comment by bnaul** [comment]
¯\\_(ツ)_/¯

**Comment by bnaul** [comment]
It was only "broken" in the sense that I forgot to change the test data...but yeah.

**Pull request merged**
