### PR TITLE
Added cython to installation process

### PR DESCRIPTION
**Pull request by bnaul**

### CODE REVIEW

**Comment by acrellin** [comment]
:+1:

**Comment by stefanv** [comment]
The `requirements.txt` file lists runtime requirements, so I don't think we should put Cython in there.

**Comment by acrellin** [comment]
Maybe we can just mention it in the installation instructions

**Comment by bnaul** [comment]
Should I add it to the `conda create ...` command?

**Comment by stefanv** [comment]
Again, this should only be in the developer instructions.  Normal users would not need to compile anything if they install using pip.  But wherever we put the "Installation from source" instructions should contain this.

**Comment by bnaul** [comment]
Got it, thanks!

**Pull request closed without merging**
