### PR TITLE
Mock out additional readthedocs libraries

### PR DESCRIPTION
**Pull request by bnaul**
Some libraries were already present on Drone (e.g. `requests`) and not readthedocs; from now on Drone should fail whenever readthedocs is missing a dependency or mock library.

Also fixes a docstring indentation warning.

### CODE REVIEW

**Comment by acrellin** [comment]
:+1:

**Comment by acrellin** [comment]
stefanv: :+1:

**Comment by stefanv** [comment]
I like how I have become a Jeff Dunham special.

**Comment by stefanv** [comment]
Also, this PR is going to come and bite us in the ass, but at least we'll know it when it happens.  Or perhaps we can build a small tool to generate a list of all external imports automatically?

**Comment by acrellin** [comment]
stefanv: :+1:

**Comment by acrellin** [comment]
:wink:

**Comment by bnaul** [comment]
¯\_(ツ)_/¯

**Comment by acrellin** [comment]
@bnaul let's look into building a tool that auto-generates a :+1: from
Stefan as soon as one of us creates a PR.

**Comment by stefanv** [comment]
What have I done.

**Pull request merged**
